DZ404114
Lab05

diff --git a/ITE/GCL08/DZ404114/Lab05/Jenkinsfile b/ITE/GCL08/DZ404114/Lab05/Jenkinsfile
--- a/ITE/GCL08/DZ404114/Lab05/Jenkinsfile
+++ b/ITE/GCL08/DZ404114/Lab05/Jenkinsfile
@@ -50,5 +50,42 @@ pipeline {
 			}
 		}
 
-       
+        stage('Prepare publish'){
+            when {
+                expression {return params.Promote}
+		    }
+            steps {
+                echo 'Preparing publish'
+                sh 'ls /var/jenkins_home/workspace/artifacts || mkdir /var/jenkins_home/workspace/artifacts'
+            }
+        }
+        
+		stage('Publish') {
+		    when {
+                expression {return params.Promote}
+		    }
+		    agent {
+                docker {
+                    image 'node:alpine'
+                    args '--rm --mount "type=volume,src=output-volume,dst=/usr/local/myapp" --mount "type=bind,source=/var/jenkins_home/workspace/artifacts,dst=/usr/local/copy" -u root:root'
+                }
+            }
+			steps {
+			    sh 'rm -rf /usr/local/copy/* || true'
+			    sh "cd /usr/local/myapp/express && npm version ${params.Version} && npm pack"
+			    sh "mv /usr/local/myapp/express/express-${params.Version}.tgz /usr/local/copy"
+			    dir('/var/jenkins_home/workspace/artifacts'){
+			        archiveArtifacts artifacts: "express-${params.Version}.tgz"
+			    }
+			}
+		}
+	}
+	post {
+        	success {
+            		echo 'Pipeline succsess'
+        	}
+        	failure {
+            		echo 'Pipeline fail'
+        	}
+    	}
 }
