changes in publish

diff --git a/ITE/GCL08/MW401139/Jenkinsfile b/ITE/GCL08/MW401139/Jenkinsfile
--- a/ITE/GCL08/MW401139/Jenkinsfile
+++ b/ITE/GCL08/MW401139/Jenkinsfile
@@ -7,6 +7,10 @@ pipeline {
         string(name: 'Build_files', defaultValue: './ITE/GCL08/MW401139', description: 'build files path')
     }
 
+     environment {
+        DOCKERHUB_CREDENTIALS = credentials('MW401139')
+    }
+
     stages {
         stage('Build') {
             steps {
@@ -28,17 +32,17 @@ pipeline {
         }
         
          
-        // stage('Deploy') {
-        //     steps {
-        //         echo 'deploying node-red'
-        //         sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
-        //         sh '''
-        //         docker images
-        //         docker tag node-red_build:latest mihaf70/mode-red-devops-deploy
-        //         docker push mihaf70/mode-red-devops-deploy
-        //         '''
-        //     }
-        // }
+        stage('Deploy') {
+            steps {
+                echo 'deploying node-red'
+                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
+                sh '''
+                docker images
+                docker tag node-red_build:latest mihaf70/mode-red-devops-deploy
+                docker push mihaf70/mode-red-devops-deploy
+                '''
+            }
+        }
 
         stage('Prepare'){
             when {
@@ -50,33 +54,33 @@ pipeline {
             }
         }
 
-        stage('Publish') {
-		    when {
-                expression {return params.Promote}
-		    }
-			steps {
-			   dir("${params.Build_files}") {
-                    sh 'docker build . -f docker_test -t node-red_test'
-				}
-                sh "ls /usr/local/node-red-publish"
-                sh "cd /usr/local/node-red-publish &&  npm version ${params.Version} && npm pack"
-                sh "ls"
-			    dir('/var/jenkins_home/workspace/artifacts'){
-			        archiveArtifacts artifacts: "node-red-${params.Version}.tgz"
-			    }
-			   
-			}
-		}
-	}
+    //    stage('Publish') {
+	// 	    when {
+    //             expression {return params.Promote}
+	// 	    }
+	// 	    agent {
+    //             docker {
+    //                 image 'node-red_build:latest'
+    //                 args '--rm --mount "type=volume,src=output-volume,dst=/usr/local/myapp" --mount "type=bind,source=/var/jenkins_home/workspace/artifacts,dst=/usr/local/copy" -u root:root'
+    //             }
+    //         }
+	// 		steps {
+	// 		    sh 'rm -rf /usr/local/copy/* || true'
+	// 		    sh "cd /usr/local/myapp/express && npm version ${params.Version} && npm pack"
+	// 		    sh "mv /usr/local/myapp/express/express-${params.Version}.tgz /usr/local/copy"
+	// 		    dir('/var/jenkins_home/workspace/artifacts'){
+	// 		        archiveArtifacts artifacts: "express-${params.Version}.tgz"
+	// 		    }
+	// 		}
+	// 	}
+	// }
+
 	post {
-        	success {
-            		echo 'Pipeline succsess'
-        	}
-        	failure {
-            		echo 'Pipeline fail'
-        	}
-
-
-
+        success {
+            echo 'Pipeline succsess'
+        }
+        failure {
+            echo 'Pipeline fail'
+        }
     }
 }
