DG401340
Lab05 - Update

diff --git a/ITE/GCL03/DG401340/Lab05/Jenkinsfile b/ITE/GCL03/DG401340/Lab05/Jenkinsfile
--- a/ITE/GCL03/DG401340/Lab05/Jenkinsfile
+++ b/ITE/GCL03/DG401340/Lab05/Jenkinsfile
@@ -38,15 +38,16 @@ pipeline {
                 sh "rm -rf ./artifacts/extract && mkdir artifacts/extract"
                 sh "cp -f ./artifacts/volume_out/target/DiscordSRV*.jar ./artifacts/extract && rm -f ./artifacts/extract/*sources* && cp -R ./artifacts/extract/. ./artifacts"
                 sh "rm -rf ./artifacts/volume_out && rm -rf ./artifacts/extract"
-                def commandStdout = sh("jar tf ./artifacts/\$(ls ./artifacts) | grep plugin.yml")
-                if(commandStdout.contains("plugin.yml"))
-                {
-                    echo "Deployed! Plugin should work."
-                } else {
-                    echo "Plugin doesn not include plugin.yml. It will not work! Aborting!"
-                    exit 1
+                script {
+                    def commandStdout = sh("jar tf ./artifacts/\$(ls ./artifacts) | grep plugin.yml")
+                    if(commandStdout.contains("plugin.yml"))
+                    {
+                        echo "Deployed! Plugin should work."
+                    } else {
+                        echo "Plugin doesn not include plugin.yml. It will not work! Aborting!"
+                        exit 1
+                    }
                 }
-                
             }
         }
         stage("Publish") {
