Update Jenkinsfile

diff --git a/ITE/GCL08/KZ303725/Lab05/Jenkinsfile b/ITE/GCL08/KZ303725/Lab05/Jenkinsfile
--- a/ITE/GCL08/KZ303725/Lab05/Jenkinsfile
+++ b/ITE/GCL08/KZ303725/Lab05/Jenkinsfile
@@ -1,73 +1,76 @@
 pipeline {
-			
-	agent any
 
-    parameters {
-        string(name: 'Version', defaultValue: '1.0.0', description: 'Version')
-        booleanParam(name: 'Promote', defaultValue: true, description: 'Promote statement')
-        string(name: 'Dockerfiles', defaultValue: './ITE/GCL08/KZ303725/Lab05', description: 'Dockerfiles path')
+  agent any
+
+  parameters {
+    string(name: 'Version', defaultValue: '1.0.0', description: 'Version')
+    booleanParam(name: 'Promote', defaultValue: true, description: 'Promote statement')
+    string(name: 'Dockerfiles', defaultValue: './ITE/GCL08/KZ303725/Lab05', description: 'Dockerfiles path')
+  }
+
+  stages {
+
+    stage('Clone') {
+      steps {
+        echo 'Cloning calculator'
+        sh 'docker volume create input-volume'
+        sh 'docker rm tempContainer || true'
+        sh 'docker run --rm --name tempContainer --mount "type=volume,src=input-volume,dst=/myapp" node bash -c "cd ~/ && ls calculator || git clone https://github.com/actionsdemos/calculator;cp -R calculator /myapp; ls /myapp"'
+      }
     }
-    
-	stages {
-	
-		stage('Clone') {
-			steps {
-				echo 'Cloning calculator'
-				sh 'docker volume create input-volume'
-				sh 'docker rm tempContainer || true'
-				sh 'docker run --rm --name tempContainer --mount "type=volume,src=input-volume,dst=/myapp" node bash -c "cd ~/ && ls calculator || git clone https://github.com/actionsdemos/calculator;cp -R calculator /myapp; ls /myapp"'
-			}
-		}
-	
-	    stage('Build') {
-			steps {
-				echo 'Buildig calculator with npm'
-				dir("${params.Dockerfiles}") {
-					sh 'docker build . -t calculator_alpine -f Dockerfile'
-					sh 'docker volume create output-volume'
-					sh 'docker rm calculator-build || true'
-					sh 'docker run --rm --name calculator-build --mount "type=volume,src=input-volume,dst=/myapp" --mount "type=volume,src=output-volume,dst=/myapp_build" calculator_alpine bash -c "cd /myapp/calculator && npm install; cp -R /myapp/calculator /myapp_build"'
-				}
-			}
-		}
 
-	    stage('Test') {
-			steps {
-				echo 'Testing calculator with npm'
-				dir("${params.Dockerfiles}") {
-					sh 'docker rm calculator-test || true'
-					sh 'docker run --rm --name calculator-test --mount "type=volume,src=input-volume,dst=/myapp_test" calculator_alpine bash -c "cd /myapp_test/calculator && npm test"'
-				}
-			}
-		}
-        
-		stage('Deploy') {
-			steps {
-				echo 'Deploying calculator'
-				sh 'docker rm -f calculator-deploy || true'
-				sh 'docker run --name calculator-deploy --mount "type=volume,src=output-volume,dst=/usr/local/myapp" calculator_alpine bash -c "cd /usr/local/myapp/calculator && npm run"'
-				sh 'sleep 5; exit $(docker inspect calculator-deploy --format="{{.State.ExitCode}}")'
-				sh 'docker rm -f calculator-deploy'
-			}
-		}
-
-        stage('Prepare publish'){
-            when {
-                expression {return params.Promote}
-		    }
-            steps {
-                echo 'Preparing publish'
-                sh 'ls /var/jenkins_home/workspace/artifacts || mkdir /var/jenkins_home/workspace/artifacts'
-            }
+    stage('Build') {
+      steps {
+        echo 'Buildig calculator with npm'
+        dir("${params.Dockerfiles}") {
+          sh 'docker build . -t calculator_alpine -f Dockerfile'
+          sh 'docker volume create output-volume'
+          sh 'docker rm calculator-build || true'
+          sh 'docker run --rm --name calculator-build --mount "type=volume,src=input-volume,dst=/myapp" --mount "type=volume,src=output-volume,dst=/myapp_build" calculator_alpine bash -c "cd /myapp/calculator && npm install; cp -R /myapp/calculator /myapp_build"'
         }
-		
-	post {
-        	success {
-            		echo 'Pipeline succsess'
-        	}
-        	failure {
-            		echo 'Pipeline fail'
-        	}
-    	}
-	}
+      }
+    }
+
+    stage('Test') {
+      steps {
+        echo 'Testing calculator with npm'
+        dir("${params.Dockerfiles}") {
+          sh 'docker rm calculator-test || true'
+          sh 'docker run --rm --name calculator-test --mount "type=volume,src=input-volume,dst=/myapp_test" calculator_alpine bash -c "cd /myapp_test/calculator && npm test"'
+        }
+      }
+    }
+
+    stage('Deploy') {
+      steps {
+        echo 'Deploying calculator'
+        sh 'docker rm -f calculator-deploy || true'
+        sh 'docker run --name calculator-deploy --mount "type=volume,src=output-volume,dst=/usr/local/myapp" calculator_alpine bash -c "cd /usr/local/myapp/calculator && npm run"'
+        sh 'sleep 5; exit $(docker inspect calculator-deploy --format="{{.State.ExitCode}}")'
+        sh 'docker rm -f calculator-deploy'
+      }
+    }
+
+    stage('Prepare publish') {
+      when {
+        expression {
+          return params.Promote
+        }
+      }
+      steps {
+        echo 'Preparing publish'
+        sh 'ls /var/jenkins_home/workspace/artifacts || mkdir /var/jenkins_home/workspace/artifacts'
+      }
+    }
+    }
+  }
+  post {
+    success {
+      echo 'Pipeline succsess'
+    }
+    failure {
+      echo 'Pipeline fail'
+    }
+  }
+}
 }
