KN401526 Lab05

diff --git a/ITE/GCL06/KN401526/Lab05/Docker_Jenkinfile b/ITE/GCL06/KN401526/Lab05/Docker_Jenkinfile
--- a/ITE/GCL06/KN401526/Lab05/Docker_Jenkinfile
+++ b/ITE/GCL06/KN401526/Lab05/Docker_Jenkinfile
@@ -58,13 +58,28 @@ pipeline
                 sh 'docker run -d --name kacper_publish --mount type=volume,src="kacper_out",dst=/usr/local/kn_proj --mount type=bind,source=/var/jenkins_home/workspace/kacper_artifacts,target=/usr/local/kn_copy node bash -c "chmod -R 777 /usr/local/kn_proj && cp -R /usr/local/kn_proj/. /usr/local/kn_copy"'
                 sh "tar -zcvf mongo-express_${params.VERSION}.tar.xz -C /var/jenkins_home/workspace/kacper_artifacts ."
                 archiveArtifacts artifacts: "mongo-express_${params.VERSION}.tar.xz"
-                sh 'docker rm -f kacper_build || true'
+                
+            }
+        } 
+        
+        stage('Clean')
+        {
+        	sh 'docker rm -f kacper_build || true'
                 sh 'docker rm -f kacper_test || true'
                 sh 'docker rm -f kacper_deploy || true'
                 sh 'docker rm -f kacper_publish || true'
-            }
         }
         
-        
       }
+      
+   post
+   {
+   	success{
+   		echo 'You successfully ended Pipline'
+   	}
+   	failure
+   	{
+   		echo 'ERROR'
+   	}
+   }   
 }
